config/routes.rb
ArtEventz::Application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  get "follows/create"
  resources :events
  resources :profiles
  devise_for :members, controllers: { registrations: "registrations"}
  root 'static_pages#index'

  match "/contact" => "static_pages#contact", via: [:get, :post]

  get "/newsletter_signup" => "static_pages#newsletter_signup"
  post "/newsletter_signup" => "static_pages#newsletter_signup"
  post "/likes/:id" => 'likes#create', as: :create_like
  post "/follows/:id" => 'follows#create', as: :create_follow
  get '/about' => 'static_pages#about'
  get '/calendar' => 'static_pages#calendar'
  get '/tos' => 'static_pages#tos'
  
  namespace :dashboard do
    resources :events do
      resources :event_photos, only: ['create']
    end
    resources :profiles do
      resources :art_photos, only: ['create']
    end
    get '/index' => 'static_pages#index'
  end
end

app/models/art_photo.rb
class ArtPhoto < ActiveRecord::Base
	mount_uploader :photo, ArtPhotoUploader
	belongs_to :profile
end

app/models/auth_token.rb
class AuthToken < ActiveRecord::Base
	belongs_to :member

end

app/models/contact.rb
class Contact < ActiveRecord::Base

	validates :name, :email, :question, presence: true
  after_create :email_contact_info

  

  private

  def email_contact_info
    AdminMailer.contact_form(self).deliver
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
	default_scope order('date ASC')
	include PgSearch
	multisearchable against: [:state]
  has_many :event_photos
  belongs_to :member
  validates :title, :date, :time, :address, :city, :state, :zip, presence: true
  acts_as_followable
  acts_as_likeable
  

end

app/models/event_photo.rb
class EventPhoto < ActiveRecord::Base
	mount_uploader :photo, EventPhotoUploader
	belongs_to :event

end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like

end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  has_many :events
  has_one :profile
  acts_as_follower
  acts_as_liker

  after_create :email_new_member

  private

  def email_new_member
    MemberMailer.delay.welcome(self)
  end

  def self.find_or_create_for_facebook(auth)
    token = AuthToken.find_or_initialize_by_email_and_provider_and_oauth_token( auth[:email], auth[:provider], auth[:token])
    token.uid = auth[:uid]
    token.save
    email = auth[:email]
    pass = auth[:uid]   #Devise.friendly_token
    user = token.member || token.create_member(email: email, password: pass, password_confirmation: pass )
  end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  has_many :art_photos
  belongs_to :member
  validates :name, presence: true
  mount_uploader :avatar, AvatarUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/dashboard/events_controller.rb
class Dashboard::EventsController < Dashboard::DashboardController

	def index
    @events = current_member.events.all
	end

	def show
    @event = Event.find(params[:id])
    @event_photo = @event.event_photos.build
	end

	def new
    @event = Event.new
    @event_photo = EventPhoto.new
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:notice] = "event has been updated."
      redirect_to dashboard_event_path(@event.id)
    else
      flash[:error] = "There was a problem updating your form."
      render :edit
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:notice] = "Event has been Destroyed"
    redirect_to dashboard_events_path
  end

  

  def create
    @event = current_member.events.build(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to dashboard_event_path(@event.id), notice: 'Event was successfully created.' }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

private

  def event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :date, :time, :tagline, :address, :address2, :city, :state, :zip, :more_info, :website, :facebook, :application_form, :contact_name, :contact_email, event_photos_attributes: [:photo, :event_id, :id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    if params[:query]
    	@events = PgSearch.multisearch(params[:query]).collect(&:searchable)
    else
    	@events = Event.all
    end
  end

  def show
    @event = Event.find(params[:id])
    @likes = @event.likers(Member)
    @follows = @event.followers(Member)
    @event_photos = @event.event_photos
    
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @event = Event.find(params[:id])
    current_member.like!(@event) 
    redirect_to event_path
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	
  def index
    @profiles = Profile.all
  end

  def show
    @profile = Profile.find(params[:id])
    @art_photos = @profile.art_photos
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  	@user = Member.find_or_create_by_email(facebook_hash)
    if @user.persisted?
			sign_in @user, event: :authentication
			redirect_to root_path, notice: "Welcome!"
		else
			flash[:alert] = "ah nu beached bru"
			redirect_to root_path
		end
  end
  
  protected
	def facebook_hash
		{}.tap do |auth|
			auth[:email] = request.env['omniauth.auth']['info']['email']
			auth[:token] = request.env['omniauth.auth']['credentials']['token']
			auth[:oauth_expires_at] = request.env['omniauth.auth']['']
			auth[:provider] = "facebook"
			auth[:uid] = request.env['omniauth.auth']['uid']
		end
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  respond_to :html, :json, :js
  
  def index
 		 if signed_in?
      redirect_to dashboard_index_path
    end
  end

  def about 
  end
  
  def calendar
    @events = Event.all
    respond_with(@events)
  end

  def contact
    @contact = Contact.new
    if request.post?
      @contact.assign_attributes(contact_params)
      @contact.save
      redirect_to contact_path, notice: "we will get back to you soon"
    end
  end 

  def tos
  end

  def newsletter_signup
    if request.post?
      MemberMailer.newsletter(params).deliver
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :question)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_title
    @page_title || "ArtEventz"
  end

	def user_logged_in?
 	  member_signed_in?
  end

  def resource_name
    :member
  end
  def resource
    @member ||= Member.new
  end
 	def devise_mapping
    @devise_mapping ||= Devise.mappings[:member]
  end
  private
  def current_user
    @current_member_log ||= Member.find(session[:member_id]) if session[:member_id]
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper


  def current_user=(user)
    @current_user ||= Member.find(session[:member_id]) if session[:member_id]
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
    <h1>Art Events</h1>
    <%= form_tag events_path, method: :get do %>
      <div class="input-prepend" id="scroller">
        <span class="add-on"><i class="icon-search"></i></span>
        <%= text_field_tag :query, params[:query], :class => "search-box", placeholder: "Type in the state" %>
      </div>
      <%= submit_tag "Search", name: nil, :class => "btn btn-search", id: "searchbtn" %>
    <% end %>
    <div class="container" id="scroller">
      <% @events.each do |event| %>
        <div class="row-events">
          <ul class="event-list">
            <li>
              <div class="event-date">
                <h5>Date:</h5>
                <%= event.date %>
              </div>
              <div class="event-title">
                <h5> Event Title:</h5>
                <%= event.title %>
              </div>
              <div class="event-location">
                <h5>Location:</h5>
                <%= event.address %><br />
                <%= event.city %><br />
                <%= event.state %>
                <div class="pull-right">
                  <%= link_to 'More Info', event_path(event.id), class: "more-info" %><br />
                </div>
              </div>
            </li>
          </ul>
        </div>
      <% end %>
    </div>

app/views/events/show.html.erb
    <p id="notice"><%= notice %></p>
    <div class="event_show_page">
      <div class="col-md-6 pull-left event_show span6">
        <br>
        <h3><%= @event.title %></h3>
        <p>
          <em><%= @event.tagline %></em>
        </p>
        <p>
          <strong>Date:</strong>
          <%= @event.date %>
        </p>
        <p>
          <strong>Time:</strong>
          <%= @event.time %>
        </p>
        <div class="small_font address">
          <p>
            <%= @event.address %> <%= @event.address2 %>
          </p>
          <p>
            <%= @event.city %>, <%= @event.state %> <%= @event.zip %>
          </p>
        </div>
        <br>
          <br>
        <p>
          Contact Name:
          <strong><%= @event.contact_name %></strong>
        </p>
        <p>
          Contact Email:
          <strong><%= @event.contact_email %></strong>
        </p>
        <br>
        <div class="small_font" id="scroller-small">
          <p>
            <%= @event.more_info %>
          </p>
        </div>
        <br>
        <br>
        <div>
          <p>
            Website:
            <%= link_to("Event Website", @event.website) %>
          </p>
          <p>
            Facebook:
            <%= link_to("Link to Facebook", @event.facebook) %>
          </p>
          <p>
            Application:
            <%= @event.application_form %>
          </p>
          <br>
        </div>
        <div>
          <% if current_member %>
            <% if @likes.include?(current_member) %>
              Likes <%= @likes.count %>
            <% else %>
              <%= link_to("Like Event", create_like_path(@event), method: :post) %>
              <%= @likes.count %>
            <% end %>
          <% else %>
            Likes <%= @likes.count %>
          <% end %>
        </div>
        <br>
        <br>
        <br>
        <p>Share this event:</p>
        <div id="socialsharing">
          <p>
          </p>
        </div>
        <br>
        <br>
        <div>
          <%= link_to 'Back', events_path %>
        </div>
      </div>
      <div class="container-fluid">
        <div class="sing_event_show">
          <%= render 'shared/single_event_photo_slider' %>
        </div>
      </div>
    </div>