config/routes.rb
ArtEventz::Application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  get "follows/create"
  resources :events
  resources :profiles
  devise_for :members, controllers: { registrations: "registrations"}
  root 'static_pages#index'

  match "/contact" => "static_pages#contact", via: [:get, :post]

  get "/newsletter_signup" => "static_pages#newsletter_signup"
  post "/newsletter_signup" => "static_pages#newsletter_signup"
  post "/likes/:id" => 'likes#create', as: :create_like
  post "/follows/:id" => 'follows#create', as: :create_follow
  get '/about' => 'static_pages#about'
  get '/calendar' => 'static_pages#calendar'
  get '/tos' => 'static_pages#tos'
  
  namespace :dashboard do
    resources :events do
      resources :event_photos, only: ['create']
    end
    resources :profiles do
      resources :art_photos, only: ['create']
    end
    get '/index' => 'static_pages#index'
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  has_many :art_photos
  belongs_to :member
  validates :name, presence: true
  mount_uploader :avatar, AvatarUploader

end

app/controllers/dashboard/art_photos_controller.rb
class Dashboard::ArtPhotosController < Dashboard::DashboardController
  before_action :find_profile

  def create
    @art_photo = @profile.art_photos.build(artphoto_params)
    if @art_photo.save
      flash[:notice] = "Art Photo has been uploaded." 
      redirect_to dashboard_profile_path(@art_photo.profile_id)
    else 
      flash[:notice] = "Whoops, something went wrong." 
    end
  end

  private

  def artphoto_params
    params.require(:art_photo).permit(:photo, :profile_id)
  end

  def find_profile
    @profile = Profile.find(params[:profile_id])
  end

end

app/controllers/dashboard/dashboard_controller.rb
class Dashboard::DashboardController < ApplicationController
  before_filter :authenticate_member!
	layout 'homepage'

end

	

app/controllers/dashboard/event_photos_controller.rb
class Dashboard::EventPhotosController < Dashboard::DashboardController
  before_action :find_event

  def create
    @event_photo = @event.event_photos.build(eventphoto_params)
    if @event_photo.save
      flash[:notice] = "Event Photo has been uploaded." 
      redirect_to dashboard_event_path(@event_photo.event_id)
    else 
      flash[:notice] = "Whoops, something went wrong." 

    end
  end

  private

  def eventphoto_params
    params.require(:event_photo).permit(:photo, :event_id)
  end

  def find_event
    @event = Event.find(params[:event_id])
  end

end

app/controllers/dashboard/events_controller.rb
class Dashboard::EventsController < Dashboard::DashboardController

	def index
    @events = current_member.events.all
	end

	def show
    @event = Event.find(params[:id])
    @event_photo = @event.event_photos.build
	end

	def new
    @event = Event.new
    @event_photo = EventPhoto.new
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:notice] = "event has been updated."
      redirect_to dashboard_event_path(@event.id)
    else
      flash[:error] = "There was a problem updating your form."
      render :edit
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:notice] = "Event has been Destroyed"
    redirect_to dashboard_events_path
  end

  

  def create
    @event = current_member.events.build(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to dashboard_event_path(@event.id), notice: 'Event was successfully created.' }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

private

  def event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :date, :time, :tagline, :address, :address2, :city, :state, :zip, :more_info, :website, :facebook, :application_form, :contact_name, :contact_email, event_photos_attributes: [:photo, :event_id, :id])
  end
end

app/controllers/dashboard/profiles_controller.rb
class Dashboard::ProfilesController < Dashboard::DashboardController

  def index
    @profile = current_member.profile
  end

  def show
    @profile = current_member.profile
    @art_photo = @profile.art_photos.build
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_member.build_profile(profile_params)
   if @profile.save
        flash[:success] = "Thanks for making a Profile with us!!"
        redirect_to dashboard_profile_path(@profile)
    else
        flash[:error] = "you are a failure and no one loves you"
        render new_dashboard_profile_path
    end
  end
 
  def destroy
    @profile = current_member.profile
    @profile.destroy
    flash[:notice] = "Profile has been Destroyed"
    redirect_to dashboard_path
  end

  def update
     @profile = Profile.find(params[:id])
       if @profile.update_attributes(profile_params)
        flash[:success] = "changes have been made"
        redirect_to dashboard_profile_path(@profile.id)
       else
        flash[:error] = "Whoops!"
        render :edit
       end
  end

  def edit
    @profile = current_member.profile
  end

  private

  def profile_params
      params.require(:profile).permit(:name, :avatar, :tagline, :website1, :website2, :website3, :facebook, :twitter, :bio)
  end

end

app/controllers/dashboard/static_pages_controller.rb
class Dashboard::StaticPagesController < Dashboard::DashboardController

	def index
		
	end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	
  def index
    @profiles = Profile.all
  end

  def show
    @profile = Profile.find(params[:id])
    @art_photos = @profile.art_photos
  end

end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/dashboard/profiles/_form.html.erb
<%= form_for([:dashboard, @profile], multipart: true ) do |f| %>


  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>
      <ul>
        <% @profile.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-5 pull-left">
    <div class="field">
      <%= f.label :name, class: 'required' %>
      <%= f.text_field :name, :placeholder => "Use full name" %>
    </div>
    <div class="field">
      <%= f.label :tagline %>
      <%= f.text_field :tagline, :placeholder => "Headline for yourself" %>
    </div>
    <div class="field">
      <%= f.label :website1 %>
      <%= f.text_field :website1, placeholder: "Include http://" %>
    </div>
    <div class="field">
      <%= f.label :website2 %>
      <%= f.text_field :website2, placeholder: "Include http://" %>
    </div>
    <div class="field">
      <%= f.label :website3 %>
      <%= f.text_field :website3, placeholder: "Include http://" %>
    </div>
    <div class="field">
      <%= f.label :bio %>
      <%= f.text_area :bio, :placeholder => "Brief description" %>
    </div>
    <div class="field">
      <%= f.label :avatar %>
      <%= f.file_field :avatar %>
    </div>
    <div class="field">
      <%= f.label :facebook %>
      <%= f.text_field :facebook, placeholder: "Include http://" %>
    </div>
    <div class="field">
      <%= f.label :twitter %>
      <%= f.text_field :twitter, :placeholder => "Twitter handle" %>
    </div>
    <div class="actions">
      <%= f.submit class: "btn btn-success" %>
    </div>
<% end %>

  

app/views/dashboard/profiles/edit.html.erb
    <div class="col-md-5">
      <h1>Edit Your Profile</h1>
      <br>
      <br>
      <%= render 'form' %>
      <p><em>Once you update a profile you will have the option to add art work</p>
      <h5><%= link_to 'Show My Profile', @profile %></h5>
    </div>

app/views/dashboard/profiles/index.html.erb
    <% if @profiles %>
      <h1>List of Profiles</h1>
      <table class="table">
        <thead>
          <tr>
            <th>Name </th>
            <th>Avatar </th>
            <th>Tagline </th>
            <th>Website </th>
            <th>Facebook </th>
            <th>Bio </th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= profile.name %></td>
            <td><%= profile.avatar %></td>
            <td><%= profile.tagline %></td>
            <td><%= profile.website %></td>
            <td><%= profile.facebook %></td>
            <td><%= profile.bio %></td>
            <td><%= link_to 'Edit', edit_dashboard_profile_path(profile) %></td>
            <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        </tbody>
      </table>
      <br>
    <% end %>

app/views/dashboard/profiles/new.html.erb
    <h1>New Profile Page</h1>
    <p>* <strong>Required field</strong></p>
    <%= render 'form' %>
    <p><em>Once you create a profile you will have the option to add art work </p>
    <h5><%= link_to 'Back', dashboard_profiles_path %></h5>

app/views/dashboard/profiles/show.html.erb
    <div class="event_show_page2">
      <div  class="col-md-4 pull-left event_show span5">
        <h3><%= @profile.name %></h3>
        <p>
          <em><%= @profile.tagline %></em>
        </p>
        <p id="avatar">
          <strong>Avatar:</strong>
          <%= image_tag(@profile.avatar.url(:medium)) %>
        </p>
        <br>
        <div class="small_font" id="scroller-small">
          <p>
            <%= @profile.bio %>
          </p>
        </div>
        <br>
        <p>
          Website:
          <%= link_to("Event Website", @profile.website1) %>
        </p>
        <p>
          Facebook:
          <%= link_to("Facebook", @profile.facebook) %>
        </p>
        <p>
          Twitter:
          <%= @profile.twitter %>
        </p>
      </div>
    </div>
    <div class="photo_in ">
      <p>Upload Art Photo:</p>
    </div>
    <br>
    <%= form_for([:dashboard, @profile, @art_photo]) do |f| %>
       <%= image_tag("#", id: "blah", width: '250px', alt: "image") %>
      <br>
      <%= f.file_field(:file, id: "imgInp") %>
      <br>
      <br>
      <br>
      <%= f.submit('Upload Image', class: 'btn btn-primary') %>
    <% end %>
    <h5>
      <%= link_to 'Edit', edit_dashboard_profile_path(@profile) %> |
      <%= link_to 'Done', @profile %>
    </h5>