config/routes.rb
ArtEventz::Application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  get "follows/create"
  resources :events
  resources :profiles
  devise_for :members, controllers: { registrations: "registrations"}
  root 'static_pages#index'

  match "/contact" => "static_pages#contact", via: [:get, :post]

  get "/newsletter_signup" => "static_pages#newsletter_signup"
  post "/newsletter_signup" => "static_pages#newsletter_signup"
  post "/likes/:id" => 'likes#create', as: :create_like
  post "/follows/:id" => 'follows#create', as: :create_follow
  get '/about' => 'static_pages#about'
  get '/calendar' => 'static_pages#calendar'
  get '/tos' => 'static_pages#tos'
  
  namespace :dashboard do
    resources :events do
      resources :event_photos, only: ['create']
    end
    resources :profiles do
      resources :art_photos, only: ['create']
    end
    get '/index' => 'static_pages#index'
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
	default_scope order('date ASC')
	include PgSearch
	multisearchable against: [:state]
  has_many :event_photos
  belongs_to :member
  validates :title, :date, :time, :address, :city, :state, :zip, presence: true
  acts_as_followable
  acts_as_likeable
  

end

app/controllers/dashboard/art_photos_controller.rb
class Dashboard::ArtPhotosController < Dashboard::DashboardController
  before_action :find_profile

  def create
    @art_photo = @profile.art_photos.build(artphoto_params)
    if @art_photo.save
      flash[:notice] = "Art Photo has been uploaded." 
      redirect_to dashboard_profile_path(@art_photo.profile_id)
    else 
      flash[:notice] = "Whoops, something went wrong." 
    end
  end

  private

  def artphoto_params
    params.require(:art_photo).permit(:photo, :profile_id)
  end

  def find_profile
    @profile = Profile.find(params[:profile_id])
  end

end

app/controllers/dashboard/dashboard_controller.rb
class Dashboard::DashboardController < ApplicationController
  before_filter :authenticate_member!
	layout 'homepage'

end

	

app/controllers/dashboard/event_photos_controller.rb
class Dashboard::EventPhotosController < Dashboard::DashboardController
  before_action :find_event

  def create
    @event_photo = @event.event_photos.build(eventphoto_params)
    if @event_photo.save
      flash[:notice] = "Event Photo has been uploaded." 
      redirect_to dashboard_event_path(@event_photo.event_id)
    else 
      flash[:notice] = "Whoops, something went wrong." 

    end
  end

  private

  def eventphoto_params
    params.require(:event_photo).permit(:photo, :event_id)
  end

  def find_event
    @event = Event.find(params[:event_id])
  end

end

app/controllers/dashboard/events_controller.rb
class Dashboard::EventsController < Dashboard::DashboardController

	def index
    @events = current_member.events.all
	end

	def show
    @event = Event.find(params[:id])
    @event_photo = @event.event_photos.build
	end

	def new
    @event = Event.new
    @event_photo = EventPhoto.new
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:notice] = "event has been updated."
      redirect_to dashboard_event_path(@event.id)
    else
      flash[:error] = "There was a problem updating your form."
      render :edit
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:notice] = "Event has been Destroyed"
    redirect_to dashboard_events_path
  end

  

  def create
    @event = current_member.events.build(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to dashboard_event_path(@event.id), notice: 'Event was successfully created.' }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

private

  def event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :date, :time, :tagline, :address, :address2, :city, :state, :zip, :more_info, :website, :facebook, :application_form, :contact_name, :contact_email, event_photos_attributes: [:photo, :event_id, :id])
  end
end

app/controllers/dashboard/profiles_controller.rb
class Dashboard::ProfilesController < Dashboard::DashboardController

  def index
    @profile = current_member.profile
  end

  def show
    @profile = current_member.profile
    @art_photo = @profile.art_photos.build
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_member.build_profile(profile_params)
   if @profile.save
        flash[:success] = "Thanks for making a Profile with us!!"
        redirect_to dashboard_profile_path(@profile)
    else
        flash[:error] = "you are a failure and no one loves you"
        render new_dashboard_profile_path
    end
  end
 
  def destroy
    @profile = current_member.profile
    @profile.destroy
    flash[:notice] = "Profile has been Destroyed"
    redirect_to dashboard_path
  end

  def update
     @profile = Profile.find(params[:id])
       if @profile.update_attributes(profile_params)
        flash[:success] = "changes have been made"
        redirect_to dashboard_profile_path(@profile.id)
       else
        flash[:error] = "Whoops!"
        render :edit
       end
  end

  def edit
    @profile = current_member.profile
  end

  private

  def profile_params
      params.require(:profile).permit(:name, :avatar, :tagline, :website1, :website2, :website3, :facebook, :twitter, :bio)
  end

end

app/controllers/dashboard/static_pages_controller.rb
class Dashboard::StaticPagesController < Dashboard::DashboardController

	def index
		
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    if params[:query]
    	@events = PgSearch.multisearch(params[:query]).collect(&:searchable)
    else
    	@events = Event.all
    end
  end

  def show
    @event = Event.find(params[:id])
    @likes = @event.likers(Member)
    @follows = @event.followers(Member)
    @event_photos = @event.event_photos
    
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/dashboard/events/_form.html.erb
 <%= nested_form_for([:dashboard, @event]) do |f| %>

  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>  
  <% end %>

    <div class="field"> 
      <%= f.label :title, class: 'required' %>
      <%= f.text_field :title %> 
    </div>
    <div class="field">
      <%= f.label :date, class: 'required' %>
      <%= f.text_field :date %>
    </div>
    <div class="field">
      <%= f.label :time, class: 'required' %>
      <%= f.time_field :time %>
    </div>
    <div class="field">
      <%= f.label :tagline %>
      <%= f.text_field :tagline %>
    </div>
    <div class="field">
      <%= f.label :address, class: 'required' %>
      <%= f.text_field :address %>
    </div>
    <div class="field">
      <%= f.label :address2 %>
      <%= f.text_field :address2 %>
    </div>
    <div class="field">
      <%= f.label :city, class: 'required' %>
      <%= f.text_field :city %>
    </div>
    <div class="field">
      <%= f.label :state, class: 'required' %>
      <%= f.text_field :state %>
    </div>
     <div class="field">
      <%= f.label :zip, class: 'required' %>
      <%= f.text_field :zip %>
    </div>

    <div class="field">
      <%= f.label :more_info %>
      <%= f.text_area :more_info %>
    </div>

    <div class="field">
      <%= f.label :website %>
      <%= f.text_field :website, placeholder: "Include http://" %>
    </div>
    <div class="field">
      <%= f.label :facebook %>
      <%= f.text_field :facebook, placeholder: "Include http://" %>
    </div>
    <div class="field">
      <%= f.label :application_form %>
      <%= f.text_field :application_form %>
    </div>
    <div class="field">
      <%= f.label :contact_name %>
      <%= f.text_field :contact_name %>
    </div>
     <div class="field">
      <%= f.label :contact_email %>
      <%= f.text_field :contact_email %>
    </div>
    <div class="actions">
      <%= f.submit class: "btn btn-success"%>
    </div>
  <% end %>

app/views/dashboard/events/edit.html.erb
    <h1>Edit an Event</h1>
    <br>
    <br>
    <%= render 'form' %>
    <p><em>Once an event is updated you will have the option to upload pictures</p>
    <h5>
      <%= link_to 'Back', dashboard_events_path %> | 
      <%= link_to 'Show Event', @event %> |
      <%= link_to 'Delete Event', dashboard_event_path(@event.id), method: :delete, data: { confirm: 'Are you sure?' } %>
    </h5>      

app/views/dashboard/events/index.html.erb
    <h1>My Events</h1>
    <table class="table">
      <thead>
        <tr>
          <th>Date </th>
          <th>Title </th>
          <th>Website </th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @events.each do |event| %>
          <tr>
            <td><%= event.date %></td>
            <td><%= event.title %></td>
            <td><%= event.website %></td>
            <td><%= link_to 'Show', dashboard_event_path(event.id) %></td>
            <td><%= link_to 'Edit', edit_dashboard_event_path(event) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>

app/views/dashboard/events/new.html.erb
    <h1>Create a New Event</h1>
    <!-- <p>DASHBOARD/NEW</p> -->
    <p>* <strong>Required field</strong></p>
    <%= render 'form' %>
    <p><em>Once an event is created you will have the option to upload pictures</p>
    <h5><%= link_to 'Back', root_path %></h5>

app/views/dashboard/events/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="event_show_page2">
  <div class="col-md-4 pull-left event_show span5">
    <h3><%= @event.title %></h3>
    <p>
    <em><%= @event.tagline %></em>
    </p>
    <br>
    <p>
    <strong>Date:</strong>
    <%= @event.date %>
    </p>
    <p>
    <strong>Time:</strong>
    <%= @event.time %>
    </p>
    <br>
    <div class="small_font address">
      <p>
      <%= @event.address %> <%= @event.address2 %>
      </p>
      <p>
      <%= @event.city %>, <%= @event.state %> <%= @event.zip %>
      </p>
      <br>
      <p>
      Contact Name:
      <strong><%= @event.contact_name %></strong>
      </p>
      <p>
      Contact Email:
      <strong><%= @event.contact_email %></strong>
      </p>
    </div>
    <br>
    <br>
    <div class="small_font">
      <div id="scroller-small">
        <p>
        <%= @event.more_info %>
        </p>
      </div>
      <br>
      <br>
      <p>
      Website:
      <%= link_to("test", @event.website) %> </p>
      <p>
      Facebook:
      <%= link_to("Link to Facebook", @event.facebook) %>
      </p>
      <p>
      Application:
      <%= @event.application_form %>
      </p>
    </div>
  </div>
  <div class="photo_in pull-right">
  </div>
  <br>
  <%= form_for([:dashboard, @event, @event_photo]) do |f| %>
  <p>Upload Event Photos</p>
  <%= image_tag("#", id: "blah", width: '250px', alt: "image") %>
  <br>
  <%= f.file_field(:file, id: "imgInp") %>
  <br>
  <br>
  <%= f.submit('Upload Image', class: 'btn btn-primary') %>
  <% end %>
  <br>
  <br>
  <br>
  <h5>
  <%= link_to 'Edit', edit_dashboard_event_path(@event) %> |
  <%= link_to 'Done', dashboard_events_path %>
  </h5>
</div>
</div>