config/routes.rb
ArtEventz::Application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  get "follows/create"
  resources :events
  resources :profiles
  devise_for :members, controllers: { registrations: "registrations"}
  root 'static_pages#index'

  match "/contact" => "static_pages#contact", via: [:get, :post]

  get "/newsletter_signup" => "static_pages#newsletter_signup"
  post "/newsletter_signup" => "static_pages#newsletter_signup"
  post "/likes/:id" => 'likes#create', as: :create_like
  post "/follows/:id" => 'follows#create', as: :create_follow
  get '/about' => 'static_pages#about'
  get '/calendar' => 'static_pages#calendar'
  get '/tos' => 'static_pages#tos'
  
  namespace :dashboard do
    resources :events do
      resources :event_photos, only: ['create']
    end
    resources :profiles do
      resources :art_photos, only: ['create']
    end
    get '/index' => 'static_pages#index'
  end
end

app/models/art_photo.rb
class ArtPhoto < ActiveRecord::Base
	mount_uploader :photo, ArtPhotoUploader
	belongs_to :profile
end

app/models/auth_token.rb
class AuthToken < ActiveRecord::Base
	belongs_to :member

end

app/models/contact.rb
class Contact < ActiveRecord::Base

	validates :name, :email, :question, presence: true
  after_create :email_contact_info

  

  private

  def email_contact_info
    AdminMailer.contact_form(self).deliver
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
	default_scope order('date ASC')
	include PgSearch
	multisearchable against: [:state]
  has_many :event_photos
  belongs_to :member
  validates :title, :date, :time, :address, :city, :state, :zip, presence: true
  acts_as_followable
  acts_as_likeable
  

end

app/models/event_photo.rb
class EventPhoto < ActiveRecord::Base
	mount_uploader :photo, EventPhotoUploader
	belongs_to :event

end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like

end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  has_many :events
  has_one :profile
  acts_as_follower
  acts_as_liker

  after_create :email_new_member

  private

  def email_new_member
    MemberMailer.delay.welcome(self)
  end

  def self.find_or_create_for_facebook(auth)
    token = AuthToken.find_or_initialize_by_email_and_provider_and_oauth_token( auth[:email], auth[:provider], auth[:token])
    token.uid = auth[:uid]
    token.save
    email = auth[:email]
    pass = auth[:uid]   #Devise.friendly_token
    user = token.member || token.create_member(email: email, password: pass, password_confirmation: pass )
  end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  has_many :art_photos
  belongs_to :member
  validates :name, presence: true
  mount_uploader :avatar, AvatarUploader

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    if params[:query]
    	@events = PgSearch.multisearch(params[:query]).collect(&:searchable)
    else
    	@events = Event.all
    end
  end

  def show
    @event = Event.find(params[:id])
    @likes = @event.likers(Member)
    @follows = @event.followers(Member)
    @event_photos = @event.event_photos
    
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @event = Event.find(params[:id])
    current_member.like!(@event) 
    redirect_to event_path
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	
  def index
    @profiles = Profile.all
  end

  def show
    @profile = Profile.find(params[:id])
    @art_photos = @profile.art_photos
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_title
    @page_title || "ArtEventz"
  end

	def user_logged_in?
 	  member_signed_in?
  end

  def resource_name
    :member
  end
  def resource
    @member ||= Member.new
  end
 	def devise_mapping
    @devise_mapping ||= Devise.mappings[:member]
  end
  private
  def current_user
    @current_member_log ||= Member.find(session[:member_id]) if session[:member_id]
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper


  def current_user=(user)
    @current_user ||= Member.find(session[:member_id]) if session[:member_id]
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <title>ArtEventz</title>
  </head>
  <body>
    <div class="topbar">
      <%= link_to(image_tag "arteventz-header-4-5.jpg") %>
    </div>
    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Home", root_path  %></li>
              <li><%= link_to "Members", profiles_path  %></li>
              <li><%= link_to "Events", events_path %></li>
              <li><%= link_to "Calendar", calendar_path  %></li>
              <li><%= link_to "About us", about_path  %></li>
              <li><%= link_to "Contact", contact_path  %></li>
              <li class="dropdown">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle">Account <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <% if user_logged_in? %>
                    <li><%= link_to "Edit Account", edit_member_registration_path %></li>
                    <li><%= link_to "Logout", destroy_member_session_path, method: :delete  %></li>
                  <% else %>
                    <li><%= link_to "Sign Up or Sign In with Facebook", "/auth/facebook", id: "sign_in" %></li>
                    <li><%= link_to "Login", new_member_session_path %></li>
                    <li><%= link_to "Sign Up", new_member_registration_path  %></li>
                  <% end %>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="span12 offset1">

        <%= bootstrap_flash %>
        <%= yield %>
      </div>
    </div>
    <footer>
      <div class="footer">
      <%= render 'shared/footer' %>
      </div>
      <div class="clearfix"></div>
    </footer>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/homepage.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ArtEventz" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>
    <div class="topbar">
      <%= link_to(image_tag "arteventz-header-4-5.jpg") %>
    </div>
    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to "Home", root_path  %></li>
              <li><%= link_to "Members", profiles_path  %></li>
              <li><%= link_to "Events", events_path %></li>
              <li><%= link_to "Calender", calendar_path  %></li>
              <li><%= link_to "About us", about_path  %></li>
              <li><%= link_to "Contact", contact_path  %></li>
              <li class="dropdown">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle">Account <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <% if user_logged_in? %>
                    <li><%= link_to "Edit Account", edit_member_registration_path %></li>
                    <li><%= link_to "Logout", destroy_member_session_path, method: :delete  %></li>
                  <% else %>
                    <li><%= link_to "Login", new_member_session_path %></li>
                    <li><%= link_to "Signup", new_member_registration_path  %></li>
                  <% end %>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2 offset1">
          <div class="sidebar-nav">
            <ul class="nav nav-list">
              <% if current_member.profile == nil %>
                <li><%= link_to "Create Event", new_dashboard_event_path  %></li>
                <li><%= link_to "Create Profile", new_dashboard_profile_path  %></li>
              <% else %>
                <li><%= link_to "My Events", dashboard_events_path  %></li>
                <li><%= link_to "My Profile", dashboard_profile_path(current_member.id)  %></li>
                <li><%= link_to "Edit Profile", edit_dashboard_profile_path(current_member.id) %></li>
                <li><%= link_to "Create Event", new_dashboard_event_path  %></li>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="span9 pull-left">
          <div>
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
    <footer>
      <div class="footer">
        <%= render 'shared/footer' %>
      </div>
      <div class="clearfix"></div>
    </footer>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/shared/_all_art_photos_slider.html.erb
<!-- primary slider for all artphotos -->
<div class="slider-wrapper theme-default">
  <div class="slider" class="nivoSlider">    
    <% @art_photos = ArtPhoto.all %>
    <% @art_photos.each do |img| %>
      <%= image_tag(img.photo.url, :title => img.profile.name) %> 
    <% end %> 
  </div>
</div>
   

app/views/shared/_all_event_photos_slider.html.erb
<!-- primary slider for all events -->
<div class="slider-wrapper theme-default">
  <div class="slider" class="nivoSlider">
    <% @event_photos = EventPhoto.all %>
    <% @event_photos.each do |img| %>
      <%= image_tag(img.photo.url, :title => img.event.title) %>
    <% end %> 
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="bottom-menu bottom-menu-large mbl">
  <div class="container foot-container">
    <div class="row">
      <div class="span2 group1">
        <p class="col-title">Featured Events</p>
        <ul class="bottom-links">
          <li><a href="http://www.artstozion.com/">A to Z Studio Tour</a></li>
          <li><a href="http://www.kayentastreetpainting.org/">Kayenta Street Paint</a></li>
          <li><a href="http://www.sgcity.org/artfestival/">St. George Art Fest</a></li>
          <li><a href="http://www.folkartmarket.org/">Santa Fe Folk Art</a></li>
          <li><a href="http://bchcares.org/foundation/art-in-the-park/">Art in the Park</a></li>
          <li><a href="http://www.artscape.org/">Baltimore Artscape </a></li>
          <li><a href="http://fineartboston.com/">Boston Int. Art Show</a></li>
        </ul>
      </div>
      <div class="span2 group1">
        <p class="col-title">Featured Artists</p>
        <ul class="bottom-links">
          <li><a href="http://www.nytimes.com/2014/04/07/arts/design/george-w-bushs-art-exhibition-at-presidential-center.html?_r=0">George W. Bush</a></li>
          <li><a href="http://www.redskelton.com/#!red-skelton-original-fine-art/c16at">Red Skelton</a></li>
          <li><a href="http://www.art.com/gallery/id--a514/georgia-o-keeffe-posters.htm">Georgia O'Keefe</a></li>
          <li><a href="https://www.facebook.com/GeraldoRivera">Geraldo Rivera</a></li>
          <li><a href="http://www.ijreview.com/2014/03/121935-ted-cruz-posters-spawn-pop-art/">Ted Cruz</a></li>
          <li><a href="http://www.allposters.com/-st/Barack-Obama-Posters_c97521_.htm">Barack Obama</a></li>
          <li><a href="http://davidhansenart.artistwebsites.com/">David Hansen</a></li>
        </ul>
      </div>
      <div class="span2 group1">
        <p class="col-title">Site Navigation</p>
        <ul class="bottom-links">
          <li><%= link_to "Sign Up", new_member_registration_path  %></li>
          <li><%= link_to "Sign In", member_session_path  %></li>
          <li><%= link_to "Contact Us", contact_path  %></li>
          <li><%= link_to "About Us", about_path  %></li>
          <li><%= link_to "Terms of Use", tos_path  %></li>
          <li><%= link_to "Get Newsletter", newsletter_signup_path  %></li>
        </ul>
      </div>
      <div class="span2 group1">
        <p class="col-title">Follow Us</p>
        <ul class="bottom-links">
          <li><a href="https://www.facebook.com/">Facebook</a></li>
          <li><a href="https://twitter.com/">Twitter</a></li>
          <li><a href="https://www.youtube.com/">Youtube</a></li>
          <li><a href="https://plus.google.com/">Google+</a></li>
        </ul>
      </div>
    </div>
  </div>
</div> 

app/views/shared/_member_art_photo_slider.html.erb
<!-- slider code for personal art sliders -->

<div class="slider-wrapper theme-default">
  <div class="ribbon"></div>
    <div class="slider" class="nivoSlider">   
      <% @art_photos.each do |img| %>
        <%= image_tag(img.photo.url, :title => img.profile.name) %>
      <% end %> 
    </div>
  </div>
</div>

app/views/shared/_single_event_photo_slider.html.erb
<!-- single event photo slider -->

<div class="slider-wrapper theme-default">
  <div class="ribbon"></div>
  <div class="slider" class="nivoSlider">           
    <% @event_photos.each do |img| %>
      <%= image_tag(img.photo.url, :title => img.event.title) %>
    <% end %>        
  </div>
</div>